// Category
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

// Product
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";


// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";